<a href="https://colab.research.google.com/github/Ayman-Abdeen/Tools/blob/main/LTE_tool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import os
import glob
import warnings
warnings.simplefilter("ignore")

In [2]:
orig_dir = os.getcwd()

In [3]:
orig_dir

'/content'

In [4]:
ZTE = pd.read_csv('/content/drive/MyDrive/LTE/History Performance_4G_DT_AlBassiouny_20230131163429.csv', skiprows=6,usecols=[1, 9, 11, 13], names=['dateid', 'cellid', 'siteid',  'Down Time - M'], parse_dates=['dateid'])
ZTE

           dateid                   cellid    siteid  Down Time - M
0      2023-01-01  LCAI1235_12352_N_Z_D3-2  LCAI1235              0
1      2023-01-01  LCAI1235_12354_N_Z_D3-4  LCAI1235              0
2      2023-01-01  LCAI1235_12353_N_Z_D3-3  LCAI1235              0
3      2023-01-01  LCAI1235_12351_N_Z_D3-1  LCAI1235              0
4      2023-01-01  LCAI1639_16392_N_Z_D3-2  LCAI1639            900
...           ...                      ...       ...            ...
112625 2023-01-31  LDEL4296_42961_N_Z_D3-1  LDEL4296              0
112626 2023-01-31  LDEL1586_15862_N_Z_D3-2  LDEL1586              0
112627 2023-01-31  LDEL1586_15864_N_Z_D3-4  LDEL1586              0
112628 2023-01-31  LDEL1586_15863_N_Z_D3-3  LDEL1586              0
112629 2023-01-31  LDEL1586_15861_N_Z_D3-1  LDEL1586              0

[112630 rows x 4 columns]

In [ ]:
HUAWEI1 = pd.read_excel('/content/drive/MyDrive/LTE/4G_HUAWEI_Update[1].xls',usecols=[0, 1, 2, 3], names=['dateid', 'siteid', 'cellid', 'Down Time - M'], parse_dates=['dateid'])
HUAWEI1

          dateid    siteid               cellid  Down Time - M
0     2023-01-08  LCAI2883  LCAI288337071NHT4-1          86395
1     2023-01-08  LCAI2883  LCAI288337072NHT4-2          86395
2     2023-01-08  LCAI2883  LCAI288337076NHT8-1          86395
3     2023-01-08  LCAI2883  LCAI288337077NHT8-2          86395
4     2023-01-08  LCAI4479  LCAI447944793NHD3-3          86385
...          ...       ...                  ...            ...
57745 2023-01-31  LCAI3402  LCAI340234024NHD3-4             20
57746 2023-01-31  LCAI3250  LCAI325032508NHG1-3             10
57747 2023-01-31  LCAI0595  LCAI059505952NHD6-2              5
57748 2023-01-31  LCAI0729  LCAI072907291NHD6-1              5
57749 2023-01-31  LCAI3145  LCAI314531456NHG1-1              5

[57750 rows x 4 columns]

In [ ]:
HUAWEI2 = pd.read_excel('/content/drive/MyDrive/LTE/4G_HUAWEI_Update[2].xls',usecols=[0, 1, 2, 3], names=['dateid', 'siteid', 'cellid', 'Down Time - M'], parse_dates=['dateid'])
HUAWEI2

          dateid    siteid               cellid  Down Time - M
0     2023-01-01  LCAI1183  LCAI118311832RHD3-2          86400
1     2023-01-01  LCAI1183  LCAI118350362SHD3-2          86400
2     2023-01-01  LCAI2893  LCAI289333801NHT4-1          86400
3     2023-01-01  LCAI2893  LCAI289333802NHT4-2          86400
4     2023-01-01  LCAI2893  LCAI289333803NHT4-3          86400
...          ...       ...                  ...            ...
37885 2023-01-07  LCAI2126  LCAI212621268NHG1-3             10
37886 2023-01-07  LCAI3394  LCAI339433949NHG1-4             10
37887 2023-01-07  LCAI2126  LCAI212621261NHD6-1              5
37888 2023-01-07  LCAI2126  LCAI212621262NHD6-2              5
37889 2023-01-07  LCAI2254  LCAI225422546NHG1-1              5

[37890 rows x 4 columns]

In [ ]:
#list dataframe you want to append
frame = [HUAWEI1, HUAWEI2]

#new dataframe to store append result
HUAWEI = pd.DataFrame()

for df in frame:
    HUAWEI = HUAWEI.append(df)

In [ ]:
HUAWEI

          dateid    siteid               cellid  Down Time - M
0     2023-01-08  LCAI2883  LCAI288337071NHT4-1          86395
1     2023-01-08  LCAI2883  LCAI288337072NHT4-2          86395
2     2023-01-08  LCAI2883  LCAI288337076NHT8-1          86395
3     2023-01-08  LCAI2883  LCAI288337077NHT8-2          86395
4     2023-01-08  LCAI4479  LCAI447944793NHD3-3          86385
...          ...       ...                  ...            ...
37885 2023-01-07  LCAI2126  LCAI212621268NHG1-3             10
37886 2023-01-07  LCAI3394  LCAI339433949NHG1-4             10
37887 2023-01-07  LCAI2126  LCAI212621261NHD6-1              5
37888 2023-01-07  LCAI2126  LCAI212621262NHD6-2              5
37889 2023-01-07  LCAI2254  LCAI225422546NHG1-1              5

[95640 rows x 4 columns]

In [ ]:
Ericsson = pd.read_excel('/content/drive/MyDrive/LTE/4G_Ericsson_update.xlsx',usecols=[1, 2, 3, 4], names=['dateid', 'siteid', 'cellid', 'Down Time - M'], parse_dates=['dateid'])
Ericsson

           dateid    siteid                   cellid  Down Time - M
0      2023-01-01  LCAI0005  LCAI0005_00051_N_E_D2-1            0.0
1      2023-01-01  LCAI0005  LCAI0005_00052_N_E_D2-2            0.0
2      2023-01-01  LCAI0005  LCAI0005_00053_N_E_D2-3            0.0
3      2023-01-01  LCAI0021  LCAI0021_00211_N_E_D2-1            0.0
4      2023-01-01  LCAI0021  LCAI0021_00212_N_E_D2-2            0.0
...           ...       ...                      ...            ...
614329 2023-01-31  TDEL4909  LDEL4909_49099_N_E_G1-4            0.0
614330 2023-01-31  TDEL4909  LDEL4909_59091_N_E_T4-1            0.0
614331 2023-01-31  TDEL4909  LDEL4909_59092_N_E_T4-2            0.0
614332 2023-01-31  TDEL4909  LDEL4909_59095_N_E_T8-1            0.0
614333 2023-01-31  TDEL4909  LDEL4909_59096_N_E_T8-2            0.0

[614334 rows x 4 columns]

In [ ]:
#all_data=myDataFrame
#all_data['Date'] = pd.to_datetime(all_data['dateid'], errors='coerce')
#count = all_data.groupby(all_data['Date'].dt.date).size()
#count

In [ ]:
#list dataframe you want to append
frame = [ZTE, HUAWEI, Ericsson]

#new dataframe to store append result
myDataFrame = pd.DataFrame()

for df in frame:
    myDataFrame = myDataFrame.append(df)

In [ ]:
myDataFrame

           dateid                   cellid    siteid  Down Time - M
0      2023-01-01  LCAI1235_12352_N_Z_D3-2  LCAI1235            0.0
1      2023-01-01  LCAI1235_12354_N_Z_D3-4  LCAI1235            0.0
2      2023-01-01  LCAI1235_12353_N_Z_D3-3  LCAI1235            0.0
3      2023-01-01  LCAI1235_12351_N_Z_D3-1  LCAI1235            0.0
4      2023-01-01  LCAI1639_16392_N_Z_D3-2  LCAI1639          900.0
...           ...                      ...       ...            ...
614329 2023-01-31  LDEL4909_49099_N_E_G1-4  TDEL4909            0.0
614330 2023-01-31  LDEL4909_59091_N_E_T4-1  TDEL4909            0.0
614331 2023-01-31  LDEL4909_59092_N_E_T4-2  TDEL4909            0.0
614332 2023-01-31  LDEL4909_59095_N_E_T8-1  TDEL4909            0.0
614333 2023-01-31  LDEL4909_59096_N_E_T8-2  TDEL4909            0.0

[822604 rows x 4 columns]

In [ ]:
len(myDataFrame)

822604

In [ ]:
len(ZTE)+len(HUAWEI)+len(Ericsson)

822604

In [ ]:
!unzip /content/drive/MyDrive/LTE/1-2023.zip -d folder

Archive:  /content/drive/MyDrive/LTE/1-2023.zip
   creating: folder/New folder(2)/
  inflating: folder/New folder(2)/LTE  referance data - Copy (17).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (18).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (19).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (20).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (21).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (22).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (23).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (24).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (25).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (26).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (27).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (28).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (29).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (30).csv
  inflating: folder/New folder(2)/LTE  referance data - Copy (31).csv
   creating: folder/New folder(1)/
  inflating: folder/New folder(1)/LTE  referance data - Copy (1).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (10).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (11).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (12).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (13).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (14).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (15).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (16).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (2).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (3).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (4).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (5).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (6).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (7).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (8).csv
  inflating: folder/New folder(1)/LTE  referance data - Copy (9).csv

In [ ]:
orig_dir="/content/folder/Newfolder(1)"
all_data1 = pd.DataFrame()

for f in glob.glob("/content/folder/Newfolder(1)/*.csv"):
    df = pd.read_csv(f, encoding= 'unicode_escape')
    all_data1 = all_data1.append(df,ignore_index=True)
    print(f)

/content/folder/Newfolder(1)/LTE  referance data - Copy (15).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (4).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (11).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (8).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (3).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (12).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (1).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (7).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (6).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (16).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (13).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (2).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (10).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (14).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (5).csv
/content/folder/Newfolder(1)/LTE  referance data - Copy (9).csv

In [ ]:
orig_dir="/content/folder/Newfolder(2)"
all_data2 = pd.DataFrame()

for f in glob.glob("/content/folder/Newfolder(2)/*.csv"):
    df = pd.read_csv(f, encoding= 'unicode_escape')
    all_data2 = all_data2.append(df,ignore_index=True)
    print(f)

/content/folder/Newfolder(2)/LTE  referance data - Copy (18).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (24).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (28).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (25).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (20).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (26).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (22).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (31).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (19).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (27).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (17).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (30).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (21).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (29).csv
/content/folder/Newfolder(2)/LTE  referance data - Copy (23).csv

In [ ]:
all_data1

,cellid,cell_name,siteid,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,dateid,outage_downtime,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/15/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/15/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/15/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/15/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/15/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594267,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/9/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594268,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,1/9/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594269,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,1/9/2023,1740.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594270,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,1/9/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594271,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,1/9/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
all_data2

,cellid,cell_name,siteid,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,dateid,outage_downtime,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/18/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/18/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/18/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/18/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/18/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557125,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,1/23/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557126,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,1/23/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557127,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,1/23/2023,1740.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557128,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,1/23/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557129,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,1/23/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#all_data=all_data2
#all_data['Date'] = pd.to_datetime(all_data['dateid'], errors='coerce')
#count = all_data.groupby(all_data['Date'].dt.date).size()
#count

In [ ]:
all_data1.to_csv('/content/drive/MyDrive/LTE/out1.csv', index=False)

In [ ]:
all_data2.to_csv('/content/drive/MyDrive/LTE/out2.csv', index=False)

In [ ]:
referance_data = pd.read_csv('/content/drive/MyDrive/LTE/out2.csv', parse_dates=['dateid'])

In [ ]:
referance_data

,cellid,cell_name,siteid,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,dateid,outage_downtime,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,2023-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,2023-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,2023-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,2023-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,2023-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557125,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,2023-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557126,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,2023-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557127,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,2023-01-23,1740.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557128,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,2023-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557129,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,2023-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
referance_data.columns

Index(['cellid', 'cell_name', 'siteid', 'celltype', 'controller', 'vendor',
       'cell_status', 'site_status', 'site_subcategory', 'area', 'zone',
       'tier', 'mrcorp', 'dateid', 'outage_downtime',
       'planned_outage_downtime', 'uptime', 'downtime', 'totaltime',
       'available_tchs', 'unavailable_tchs', 'configured_tchs',
       'planned_outage_tch_loss'],
      dtype='object')

In [ ]:
myDataFrame.columns

Index(['dateid', 'cellid', 'siteid', 'Down Time - M'], dtype='object')

In [ ]:
s = 'dateid' == 'dateid'
s

True

In [ ]:
d='cellid'=='cellid'
d

True

In [ ]:
myDataFrame

           dateid                   cellid    siteid  Down Time - M
0      2023-01-01  LCAI1235_12352_N_Z_D3-2  LCAI1235            0.0
1      2023-01-01  LCAI1235_12354_N_Z_D3-4  LCAI1235            0.0
2      2023-01-01  LCAI1235_12353_N_Z_D3-3  LCAI1235            0.0
3      2023-01-01  LCAI1235_12351_N_Z_D3-1  LCAI1235            0.0
4      2023-01-01  LCAI1639_16392_N_Z_D3-2  LCAI1639          900.0
...           ...                      ...       ...            ...
614329 2023-01-31  LDEL4909_49099_N_E_G1-4  TDEL4909            0.0
614330 2023-01-31  LDEL4909_59091_N_E_T4-1  TDEL4909            0.0
614331 2023-01-31  LDEL4909_59092_N_E_T4-2  TDEL4909            0.0
614332 2023-01-31  LDEL4909_59095_N_E_T8-1  TDEL4909            0.0
614333 2023-01-31  LDEL4909_59096_N_E_T8-2  TDEL4909            0.0

[822604 rows x 4 columns]

In [ ]:
result = pd.merge(referance_data, myDataFrame, how="left", on=['dateid','cellid'])
result

,cellid,cell_name,siteid_x,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss,siteid_y,Down Time - M
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560150,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560151,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LCAI2490,0.0
560152,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MCAI0650,0.0
560153,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MCAI5260,0.0
560154,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LCAI5298,0.0

In [ ]:
result.describe()

,outage_downtime,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss,Down Time - M
count,35397.000000,750.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,327944.000000
mean,3614.282566,1848.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.070735
std,7744.534897,1477.131417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1948.025620
min,0.000000,420.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,120.000000,420.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,780.000000,1320.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,3780.000000,3060.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
max,60480.000000,4740.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86400.000000

In [ ]:
result.to_csv('/content/drive/MyDrive/LTE/dataframeout2.csv', index=False)

In [ ]:

!sudo pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xlsxwriter
  Downloading XlsxWriter-3.0.8-py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 KB 3.9 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.0.8

In [ ]:
writer = pd.ExcelWriter("dataframe.xlsx", engine='xlsxwriter')
result.to_excel(writer,sheet_name = 'sheet1', index=False)
writer.save()

ValueError: ignored

In [23]:
ava_data = pd.read_csv('/content/drive/MyDrive/LTE/dataframeout1.csv', parse_dates=['dateid'])

In [24]:
ava_data

,cellid,cell_name,siteid_x,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss,siteid_y,Down Time - M
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594701,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594702,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LCAI2490,0.0
594703,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MCAI0650,0.0
594704,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MCAI5260,0.0
594705,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LCAI5298,0.0

In [ ]:
varcov = df_koersen.pct_change().apply(lambda x: np.log(x+1)).cov

df_koersen.set_index('Date')

varcov = df_koersen.pct_change().apply(lambda x: np.log(x+1)).cov

In [25]:
ava_data['Down Time - M'] = ava_data['Down Time - M'].div(60)

In [26]:
ava_data['Down Time - M'].max()

1440.0

In [27]:
ava_data

,cellid,cell_name,siteid_x,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss,siteid_y,Down Time - M
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594701,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594702,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LCAI2490,0.0
594703,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MCAI0650,0.0
594704,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MCAI5260,0.0
594705,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LCAI5298,0.0

In [29]:
outage = pd.read_excel('/content/drive/MyDrive/LTE/Accumulated Outage.xlsx',usecols=[0, 11, 39, 50], names=['siteid_y', 'outage-Down Time - M', 'dateid', 'ServiceType'], parse_dates=['dateid'])
#outage

In [30]:
result = pd.merge(ava_data, outage, how="left", on=['dateid','siteid_y'])
result

,cellid,cell_name,siteid_x,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss,siteid_y,Down Time - M,outage-Down Time - M,ServiceType
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605396,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605397,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,LCAI2490,0.0,NaN,NaN
605398,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,NaN,MCAI0650,0.0,NaN,NaN
605399,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,MCAI5260,0.0,NaN,NaN
605400,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,NaN,LCAI5298,0.0,NaN,NaN

In [31]:
result.describe()

,outage_downtime,planned_outage_downtime,uptime,downtime,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss,Down Time - M,outage-Down Time - M
count,39381.000000,826.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,357335.000000,20393.000000
mean,3546.621467,1838.789346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.614255,37.184426
std,7640.539817,1455.823328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.000363,109.987426
min,0.000000,420.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
25%,120.000000,420.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,2.000000
50%,720.000000,1320.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,5.000000
75%,3720.000000,3060.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,19.000000
max,60480.000000,4740.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1440.000000,1440.000000

In [33]:
result['Total Down Time - M'] = result['Down Time - M'] + result['outage-Down Time - M']

In [34]:
result

,cellid,cell_name,siteid_x,celltype,controller,vendor,cell_status,site_status,site_subcategory,area,...,totaltime,available_tchs,unavailable_tchs,configured_tchs,planned_outage_tch_loss,siteid_y,Down Time - M,outage-Down Time - M,ServiceType,Total Down Time - M
0,LCAI1330_13301_N_H_D3-1,LCAI1330_13301_N_H_D3-1,LCAI1330,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LCAI2157_21570_X_H_D6-1,LCAI2157_21570_X_H_D6-1,LCAI2157,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCAI1484_14841_N_H_D3-1,LCAI1484_14841_N_H_D3-1,LCAI1484,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LCAI3512_35123_N_H_D7-3,LCAI3512_35123_N_H_D7-3,LCAI3512,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LCAI0770_07706_N_H_G1-1,LCAI0770_07706_N_H_G1-1,ULCAI0770,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605396,LCAI1832_52094_N_H_T4-4,LCAI1832_52094_N_H_T4-4,LCAI1832,LTE,LTE_Huawei,Huawei,ON AIR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605397,LCAI2490_24908_N_Z_G1-4,LCAI2490_24908_N_Z_G1-4,LCAI2490,LTE,LTE_ZTE,ZTE,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,LCAI2490,0.0,NaN,NaN,NaN
605398,LCAI0650_57515_N_E_T8-1,LCAI0650_57515_N_E_T8-1,LCAI0650,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Gesr El Suiz,...,NaN,NaN,NaN,NaN,NaN,MCAI0650,0.0,NaN,NaN,NaN
605399,LCAI5260_52607_N_E_G1-3,LCAI5260_52607_N_E_G1-3,LCAI5260,LTE,LTE,Ericsson,ON AIR,ON AIR,FM Inspection,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,MCAI5260,0.0,NaN,NaN,NaN
605400,LCAI5298_52981_I_E_D1-1,LCAI5298_52981_I_E_D1-1,LCAI5298,LTE,LTE,Ericsson,ON AIR,ON AIR,EOT,Tagamo3,...,NaN,NaN,NaN,NaN,NaN,LCAI5298,0.0,NaN,NaN,NaN

In [35]:
result.to_csv('/content/drive/MyDrive/LTE/FinalDataFrameout.csv', index=False)